services:
  nestjsApp_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
  mysql_db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nestjs
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_TCP_PORT=3306